// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptionsTracker.Data;

#nullable disable

namespace OptionsTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OptionsTracker.Models.OptionsPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Contracts")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OptionType")
                        .HasColumnType("int");

                    b.Property<decimal>("PremiumPerContract")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("RolledFromId")
                        .HasColumnType("int");

                    b.Property<int?>("RolledToId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Strategy")
                        .HasColumnType("int");

                    b.Property<decimal>("StrikePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("UnderlyingPositionId")
                        .HasColumnType("int");

                    b.Property<string>("UnderlyingSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ExpirationDate");

                    b.HasIndex("RolledFromId")
                        .IsUnique()
                        .HasFilter("[RolledFromId] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("UnderlyingPositionId");

                    b.HasIndex("UnderlyingSymbol");

                    b.ToTable("OptionsPositions");
                });

            modelBuilder.Entity("OptionsTracker.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Account");

                    b.HasIndex("Symbol");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("OptionsTracker.Models.RollHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromOptionsPositionId")
                        .HasColumnType("int");

                    b.Property<decimal>("NetCredit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RollDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToOptionsPositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromOptionsPositionId");

                    b.HasIndex("ToOptionsPositionId");

                    b.ToTable("RollHistories");
                });

            modelBuilder.Entity("OptionsTracker.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OptionType")
                        .HasColumnType("int");

                    b.Property<int?>("OptionsPositionId")
                        .HasColumnType("int");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("StrikePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Account");

                    b.HasIndex("OptionsPositionId");

                    b.HasIndex("PositionId");

                    b.HasIndex("Symbol");

                    b.HasIndex("TransactionDate");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OptionsTracker.Models.OptionsPosition", b =>
                {
                    b.HasOne("OptionsTracker.Models.OptionsPosition", "RolledFrom")
                        .WithOne("RolledTo")
                        .HasForeignKey("OptionsTracker.Models.OptionsPosition", "RolledFromId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OptionsTracker.Models.Position", "UnderlyingPosition")
                        .WithMany("CoveredCalls")
                        .HasForeignKey("UnderlyingPositionId");

                    b.Navigation("RolledFrom");

                    b.Navigation("UnderlyingPosition");
                });

            modelBuilder.Entity("OptionsTracker.Models.RollHistory", b =>
                {
                    b.HasOne("OptionsTracker.Models.OptionsPosition", "FromPosition")
                        .WithMany()
                        .HasForeignKey("FromOptionsPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptionsTracker.Models.OptionsPosition", "ToPosition")
                        .WithMany()
                        .HasForeignKey("ToOptionsPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromPosition");

                    b.Navigation("ToPosition");
                });

            modelBuilder.Entity("OptionsTracker.Models.Transaction", b =>
                {
                    b.HasOne("OptionsTracker.Models.OptionsPosition", "OptionsPosition")
                        .WithMany("Transactions")
                        .HasForeignKey("OptionsPositionId");

                    b.HasOne("OptionsTracker.Models.Position", "Position")
                        .WithMany("Transactions")
                        .HasForeignKey("PositionId");

                    b.Navigation("OptionsPosition");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("OptionsTracker.Models.OptionsPosition", b =>
                {
                    b.Navigation("RolledTo");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("OptionsTracker.Models.Position", b =>
                {
                    b.Navigation("CoveredCalls");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
